package controller;

public enum Event {
	HIDE_PASSWORD, LOGIN_ACCOUNT, GET_LOGIN_DATA, 
	GET_CREATE_DATA, CANCEL_NEW_ACCOUNT, ADD_COURSE_TH, 
	MODIFY_COURSE_TH, DELETE_COURSE_BTN, BTN_COURSE, 
	VISIBLE_CONF_COURSE, INSERT_COURSE, VISIBLE_DELETE_COURSE_BOX, 
	VISIBLE_MOD_COURSE, VISIBLE_DELETE_COURSE_BTN, CONFIRM_DELETE_COURSE,
	ADD_SCHEDULE_COURSE, BTN_MODIFY, DELETE_SCHEDULE_COURSE, 
	CONFIRM_MODIFY_COURSE_TH
}