package controller;

public enum Event {
	HIDE_PASSWORD, LOGIN_ACCOUNT, GET_LOGIN_DATA, GET_CREATE_DATA, CANCEL_NEW_ACCOUNT, ADD_COURSE_TH, MODIFY_COURSE_TH,
	DELETE_COURSE_OR_HOMEWORK, ADD_OR_MOD_ACTIVITY_ST, AVG_ST, DELETE_ACTIVITY_ST, SHOW_SCHEDULE,
	BTN_COURSE, FIND_INFO_ADD_COURSE, VISIBLE_CONF_COURSE, INSERT_COURSE, VISIBLE_SCHEDULE,
	VISIBLE_HOMEWORK, VISIBLE_MOD_COURSE, FIND_HOMEWORK, FIND_INFO_HOMEWORK, ADD_OR_MODIFY_HOMEWORK, FIND_HOMEWORK_DELETE,
	DELETE_COURSE, CONFIRM_DELETE_COURSE, CONFIRM_DELETE_HOMEWORK, DELETE_HOMEWORK, DELETE_ACTIVITY,
	CONFIRM_DELETE_ACTIVITY, CALCULATE_AVG, MODIFY_ACTIVITY, SEND_ACTIVITY,
	RESET_DELETE_ACTIVITY, VISIBLE_AVG, ACTION_SCHEDULER_BTN, ADD_SCHEDULE_COURSE, BTN_MODIFY, DELETE_SCHEDULE_COURSE, CONFIRM_MODIFY_COURSE_TH

}
